### ISSUE TITLE
Add a redirect_url to the custom AuthOAuthView

### ISSUE THREAD

**Issue by craigappl** [onaio/superset-patchup#27]
The custom AuthOAuthView doesn't support redirecting after the user is logged in as an oAuth provider. The OpenLMIS project requires this functionality to support embedding the solution within the iFrame.

- [x] Review what was committed before: https://github.com/OpenLMIS/openlmis-ref-distro/blob/651c1245a3ea1c76532f47fefc2ebdda8bea68d1/reporting/config/services/superset/security.py#L11-L43 (the login function appears to be missing from our custom AuthOAuthView)
- [x] Add the login function to the to the AuthOAuthView

**Comment by craigappl** [comment]
@Wambere , I was looking at the code today and realized I don't have a good enough understanding of Python to commit it. 

Here's what I think needs to happen:
1. Copy this text over to the oAuth.py file: https://github.com/OpenLMIS/openlmis-ref-distro/blob/651c1245a3ea1c76532f47fefc2ebdda8bea68d1/reporting/config/services/superset/security.py#L11-L43
2. Update the imports so we don't get into dependency issues
3. This section needs to be deleted https://github.com/OpenLMIS/openlmis-ref-distro/blob/651c1245a3ea1c76532f47fefc2ebdda8bea68d1/reporting/config/services/superset/security.py#L18-L23
4. Insert this code https://github.com/onaio/superset-patchup/blob/master/superset_patchup/oauth.py#L65-L79 at https://github.com/OpenLMIS/openlmis-ref-distro/blob/651c1245a3ea1c76532f47fefc2ebdda8bea68d1/reporting/config/services/superset/security.py#L27
5. Deploy and test on UAT
6. If it works, create a new version of the patch-up
7. Update the openlmis-ref-distro code to pull in the latest version of patch-up
8. Redeploy the UAT reporting stack with the new code and test it

**Comment by Wambere** [comment]
The login function with a redirect variable has been added by #29 
This however does not fully work as previously stated. 

In order to be redirected to a specified url or dashboard, a user needs to be logged into superset. Which means that the first time a user tries to access a dashboard (if they are not logged in) they will be logged in and then redirected to the main dashboards page. But if they try another dashboard, since the first attempt logged them in, every subsequent request will redirect successfully.
